/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as StackRouteImport } from './routes/stack'
import { Route as SdkRouteImport } from './routes/sdk'
import { Route as OasfRouteImport } from './routes/oasf'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as BotRouteImport } from './routes/bot'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AboutRouteImport } from './routes/about'
import { Route as A2aRouteImport } from './routes/a2a'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as StatsIndexRouteImport } from './routes/stats.index'
import { Route as McpIndexRouteImport } from './routes/mcp.index'
import { Route as ToolsWriteRouteImport } from './routes/tools.write'
import { Route as ToolsReadRouteImport } from './routes/tools.read'
import { Route as ToolsPrepareRouteImport } from './routes/tools.prepare'
import { Route as StatsPackageRouteImport } from './routes/stats.package'
import { Route as StatsOnchainRouteImport } from './routes/stats.onchain'
import { Route as StatsOffchainRouteImport } from './routes/stats.offchain'
import { Route as McpRemoteRouteImport } from './routes/mcp.remote'
import { Route as McpLocalRouteImport } from './routes/mcp.local'
import { Route as ToolsCategoryIndexRouteImport } from './routes/tools.$category.index'
import { Route as ToolsCategoryToolSlugRouteImport } from './routes/tools.$category.$toolSlug'
import { Route as GooddollarVerifyCallbackRouteImport } from './routes/gooddollar.verify.callback'
import { Route as ApiCronAmplitudeSyncRouteImport } from './routes/api/cron/amplitude-sync'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const SdkRoute = SdkRouteImport.update({
  id: '/sdk',
  path: '/sdk',
  getParentRoute: () => rootRouteImport,
} as any)
const OasfRoute = OasfRouteImport.update({
  id: '/oasf',
  path: '/oasf',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const BotRoute = BotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const A2aRoute = A2aRouteImport.update({
  id: '/a2a',
  path: '/a2a',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StatsRoute,
} as any)
const McpIndexRoute = McpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => McpRoute,
} as any)
const ToolsWriteRoute = ToolsWriteRouteImport.update({
  id: '/tools/write',
  path: '/tools/write',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsReadRoute = ToolsReadRouteImport.update({
  id: '/tools/read',
  path: '/tools/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPrepareRoute = ToolsPrepareRouteImport.update({
  id: '/tools/prepare',
  path: '/tools/prepare',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsPackageRoute = StatsPackageRouteImport.update({
  id: '/package',
  path: '/package',
  getParentRoute: () => StatsRoute,
} as any)
const StatsOnchainRoute = StatsOnchainRouteImport.update({
  id: '/onchain',
  path: '/onchain',
  getParentRoute: () => StatsRoute,
} as any)
const StatsOffchainRoute = StatsOffchainRouteImport.update({
  id: '/offchain',
  path: '/offchain',
  getParentRoute: () => StatsRoute,
} as any)
const McpRemoteRoute = McpRemoteRouteImport.update({
  id: '/remote',
  path: '/remote',
  getParentRoute: () => McpRoute,
} as any)
const McpLocalRoute = McpLocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => McpRoute,
} as any)
const ToolsCategoryIndexRoute = ToolsCategoryIndexRouteImport.update({
  id: '/tools/$category/',
  path: '/tools/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCategoryToolSlugRoute = ToolsCategoryToolSlugRouteImport.update({
  id: '/tools/$category/$toolSlug',
  path: '/tools/$category/$toolSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const GooddollarVerifyCallbackRoute =
  GooddollarVerifyCallbackRouteImport.update({
    id: '/gooddollar/verify/callback',
    path: '/gooddollar/verify/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronAmplitudeSyncRoute = ApiCronAmplitudeSyncRouteImport.update({
  id: '/cron/amplitude-sync',
  path: '/cron/amplitude-sync',
  getParentRoute: () => ApiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a2a': typeof A2aRoute
  '/about': typeof AboutRoute
  '/api': typeof ApiRouteWithChildren
  '/bot': typeof BotRoute
  '/mcp': typeof McpRouteWithChildren
  '/oasf': typeof OasfRoute
  '/sdk': typeof SdkRoute
  '/stack': typeof StackRoute
  '/stats': typeof StatsRouteWithChildren
  '/mcp/local': typeof McpLocalRoute
  '/mcp/remote': typeof McpRemoteRoute
  '/stats/offchain': typeof StatsOffchainRoute
  '/stats/onchain': typeof StatsOnchainRoute
  '/stats/package': typeof StatsPackageRoute
  '/tools/prepare': typeof ToolsPrepareRoute
  '/tools/read': typeof ToolsReadRoute
  '/tools/write': typeof ToolsWriteRoute
  '/mcp/': typeof McpIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/cron/amplitude-sync': typeof ApiCronAmplitudeSyncRoute
  '/gooddollar/verify/callback': typeof GooddollarVerifyCallbackRoute
  '/tools/$category/$toolSlug': typeof ToolsCategoryToolSlugRoute
  '/tools/$category/': typeof ToolsCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a2a': typeof A2aRoute
  '/about': typeof AboutRoute
  '/api': typeof ApiRouteWithChildren
  '/bot': typeof BotRoute
  '/oasf': typeof OasfRoute
  '/sdk': typeof SdkRoute
  '/stack': typeof StackRoute
  '/mcp/local': typeof McpLocalRoute
  '/mcp/remote': typeof McpRemoteRoute
  '/stats/offchain': typeof StatsOffchainRoute
  '/stats/onchain': typeof StatsOnchainRoute
  '/stats/package': typeof StatsPackageRoute
  '/tools/prepare': typeof ToolsPrepareRoute
  '/tools/read': typeof ToolsReadRoute
  '/tools/write': typeof ToolsWriteRoute
  '/mcp': typeof McpIndexRoute
  '/stats': typeof StatsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/api/cron/amplitude-sync': typeof ApiCronAmplitudeSyncRoute
  '/gooddollar/verify/callback': typeof GooddollarVerifyCallbackRoute
  '/tools/$category/$toolSlug': typeof ToolsCategoryToolSlugRoute
  '/tools/$category': typeof ToolsCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a2a': typeof A2aRoute
  '/about': typeof AboutRoute
  '/api': typeof ApiRouteWithChildren
  '/bot': typeof BotRoute
  '/mcp': typeof McpRouteWithChildren
  '/oasf': typeof OasfRoute
  '/sdk': typeof SdkRoute
  '/stack': typeof StackRoute
  '/stats': typeof StatsRouteWithChildren
  '/mcp/local': typeof McpLocalRoute
  '/mcp/remote': typeof McpRemoteRoute
  '/stats/offchain': typeof StatsOffchainRoute
  '/stats/onchain': typeof StatsOnchainRoute
  '/stats/package': typeof StatsPackageRoute
  '/tools/prepare': typeof ToolsPrepareRoute
  '/tools/read': typeof ToolsReadRoute
  '/tools/write': typeof ToolsWriteRoute
  '/mcp/': typeof McpIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/cron/amplitude-sync': typeof ApiCronAmplitudeSyncRoute
  '/gooddollar/verify/callback': typeof GooddollarVerifyCallbackRoute
  '/tools/$category/$toolSlug': typeof ToolsCategoryToolSlugRoute
  '/tools/$category/': typeof ToolsCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a2a'
    | '/about'
    | '/api'
    | '/bot'
    | '/mcp'
    | '/oasf'
    | '/sdk'
    | '/stack'
    | '/stats'
    | '/mcp/local'
    | '/mcp/remote'
    | '/stats/offchain'
    | '/stats/onchain'
    | '/stats/package'
    | '/tools/prepare'
    | '/tools/read'
    | '/tools/write'
    | '/mcp/'
    | '/stats/'
    | '/tools/'
    | '/api/cron/amplitude-sync'
    | '/gooddollar/verify/callback'
    | '/tools/$category/$toolSlug'
    | '/tools/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a2a'
    | '/about'
    | '/api'
    | '/bot'
    | '/oasf'
    | '/sdk'
    | '/stack'
    | '/mcp/local'
    | '/mcp/remote'
    | '/stats/offchain'
    | '/stats/onchain'
    | '/stats/package'
    | '/tools/prepare'
    | '/tools/read'
    | '/tools/write'
    | '/mcp'
    | '/stats'
    | '/tools'
    | '/api/cron/amplitude-sync'
    | '/gooddollar/verify/callback'
    | '/tools/$category/$toolSlug'
    | '/tools/$category'
  id:
    | '__root__'
    | '/'
    | '/a2a'
    | '/about'
    | '/api'
    | '/bot'
    | '/mcp'
    | '/oasf'
    | '/sdk'
    | '/stack'
    | '/stats'
    | '/mcp/local'
    | '/mcp/remote'
    | '/stats/offchain'
    | '/stats/onchain'
    | '/stats/package'
    | '/tools/prepare'
    | '/tools/read'
    | '/tools/write'
    | '/mcp/'
    | '/stats/'
    | '/tools/'
    | '/api/cron/amplitude-sync'
    | '/gooddollar/verify/callback'
    | '/tools/$category/$toolSlug'
    | '/tools/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  A2aRoute: typeof A2aRoute
  AboutRoute: typeof AboutRoute
  ApiRoute: typeof ApiRouteWithChildren
  BotRoute: typeof BotRoute
  McpRoute: typeof McpRouteWithChildren
  OasfRoute: typeof OasfRoute
  SdkRoute: typeof SdkRoute
  StackRoute: typeof StackRoute
  StatsRoute: typeof StatsRouteWithChildren
  ToolsPrepareRoute: typeof ToolsPrepareRoute
  ToolsReadRoute: typeof ToolsReadRoute
  ToolsWriteRoute: typeof ToolsWriteRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  GooddollarVerifyCallbackRoute: typeof GooddollarVerifyCallbackRoute
  ToolsCategoryToolSlugRoute: typeof ToolsCategoryToolSlugRoute
  ToolsCategoryIndexRoute: typeof ToolsCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdk': {
      id: '/sdk'
      path: '/sdk'
      fullPath: '/sdk'
      preLoaderRoute: typeof SdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oasf': {
      id: '/oasf'
      path: '/oasf'
      fullPath: '/oasf'
      preLoaderRoute: typeof OasfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot': {
      id: '/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof BotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a2a': {
      id: '/a2a'
      path: '/a2a'
      fullPath: '/a2a'
      preLoaderRoute: typeof A2aRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/'
      fullPath: '/stats/'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof StatsRoute
    }
    '/mcp/': {
      id: '/mcp/'
      path: '/'
      fullPath: '/mcp/'
      preLoaderRoute: typeof McpIndexRouteImport
      parentRoute: typeof McpRoute
    }
    '/tools/write': {
      id: '/tools/write'
      path: '/tools/write'
      fullPath: '/tools/write'
      preLoaderRoute: typeof ToolsWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/read': {
      id: '/tools/read'
      path: '/tools/read'
      fullPath: '/tools/read'
      preLoaderRoute: typeof ToolsReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/prepare': {
      id: '/tools/prepare'
      path: '/tools/prepare'
      fullPath: '/tools/prepare'
      preLoaderRoute: typeof ToolsPrepareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/package': {
      id: '/stats/package'
      path: '/package'
      fullPath: '/stats/package'
      preLoaderRoute: typeof StatsPackageRouteImport
      parentRoute: typeof StatsRoute
    }
    '/stats/onchain': {
      id: '/stats/onchain'
      path: '/onchain'
      fullPath: '/stats/onchain'
      preLoaderRoute: typeof StatsOnchainRouteImport
      parentRoute: typeof StatsRoute
    }
    '/stats/offchain': {
      id: '/stats/offchain'
      path: '/offchain'
      fullPath: '/stats/offchain'
      preLoaderRoute: typeof StatsOffchainRouteImport
      parentRoute: typeof StatsRoute
    }
    '/mcp/remote': {
      id: '/mcp/remote'
      path: '/remote'
      fullPath: '/mcp/remote'
      preLoaderRoute: typeof McpRemoteRouteImport
      parentRoute: typeof McpRoute
    }
    '/mcp/local': {
      id: '/mcp/local'
      path: '/local'
      fullPath: '/mcp/local'
      preLoaderRoute: typeof McpLocalRouteImport
      parentRoute: typeof McpRoute
    }
    '/tools/$category/': {
      id: '/tools/$category/'
      path: '/tools/$category'
      fullPath: '/tools/$category/'
      preLoaderRoute: typeof ToolsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$category/$toolSlug': {
      id: '/tools/$category/$toolSlug'
      path: '/tools/$category/$toolSlug'
      fullPath: '/tools/$category/$toolSlug'
      preLoaderRoute: typeof ToolsCategoryToolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gooddollar/verify/callback': {
      id: '/gooddollar/verify/callback'
      path: '/gooddollar/verify/callback'
      fullPath: '/gooddollar/verify/callback'
      preLoaderRoute: typeof GooddollarVerifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/amplitude-sync': {
      id: '/api/cron/amplitude-sync'
      path: '/cron/amplitude-sync'
      fullPath: '/api/cron/amplitude-sync'
      preLoaderRoute: typeof ApiCronAmplitudeSyncRouteImport
      parentRoute: typeof ApiRoute
    }
  }
}

interface ApiRouteChildren {
  ApiCronAmplitudeSyncRoute: typeof ApiCronAmplitudeSyncRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiCronAmplitudeSyncRoute: ApiCronAmplitudeSyncRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

interface McpRouteChildren {
  McpLocalRoute: typeof McpLocalRoute
  McpRemoteRoute: typeof McpRemoteRoute
  McpIndexRoute: typeof McpIndexRoute
}

const McpRouteChildren: McpRouteChildren = {
  McpLocalRoute: McpLocalRoute,
  McpRemoteRoute: McpRemoteRoute,
  McpIndexRoute: McpIndexRoute,
}

const McpRouteWithChildren = McpRoute._addFileChildren(McpRouteChildren)

interface StatsRouteChildren {
  StatsOffchainRoute: typeof StatsOffchainRoute
  StatsOnchainRoute: typeof StatsOnchainRoute
  StatsPackageRoute: typeof StatsPackageRoute
  StatsIndexRoute: typeof StatsIndexRoute
}

const StatsRouteChildren: StatsRouteChildren = {
  StatsOffchainRoute: StatsOffchainRoute,
  StatsOnchainRoute: StatsOnchainRoute,
  StatsPackageRoute: StatsPackageRoute,
  StatsIndexRoute: StatsIndexRoute,
}

const StatsRouteWithChildren = StatsRoute._addFileChildren(StatsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  A2aRoute: A2aRoute,
  AboutRoute: AboutRoute,
  ApiRoute: ApiRouteWithChildren,
  BotRoute: BotRoute,
  McpRoute: McpRouteWithChildren,
  OasfRoute: OasfRoute,
  SdkRoute: SdkRoute,
  StackRoute: StackRoute,
  StatsRoute: StatsRouteWithChildren,
  ToolsPrepareRoute: ToolsPrepareRoute,
  ToolsReadRoute: ToolsReadRoute,
  ToolsWriteRoute: ToolsWriteRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  GooddollarVerifyCallbackRoute: GooddollarVerifyCallbackRoute,
  ToolsCategoryToolSlugRoute: ToolsCategoryToolSlugRoute,
  ToolsCategoryIndexRoute: ToolsCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
