/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SdkRouteImport } from './routes/sdk'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as StatsIndexRouteImport } from './routes/stats.index'
import { Route as StatsPackageRouteImport } from './routes/stats.package'
import { Route as StatsOnchainRouteImport } from './routes/stats.onchain'
import { Route as StatsOffchainRouteImport } from './routes/stats.offchain'
import { Route as ToolsCategoryIndexRouteImport } from './routes/tools.$category.index'
import { Route as ToolsCategoryToolSlugRouteImport } from './routes/tools.$category.$toolSlug'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SdkRoute = SdkRouteImport.update({
  id: '/sdk',
  path: '/sdk',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StatsRoute,
} as any)
const StatsPackageRoute = StatsPackageRouteImport.update({
  id: '/package',
  path: '/package',
  getParentRoute: () => StatsRoute,
} as any)
const StatsOnchainRoute = StatsOnchainRouteImport.update({
  id: '/onchain',
  path: '/onchain',
  getParentRoute: () => StatsRoute,
} as any)
const StatsOffchainRoute = StatsOffchainRouteImport.update({
  id: '/offchain',
  path: '/offchain',
  getParentRoute: () => StatsRoute,
} as any)
const ToolsCategoryIndexRoute = ToolsCategoryIndexRouteImport.update({
  id: '/tools/$category/',
  path: '/tools/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCategoryToolSlugRoute = ToolsCategoryToolSlugRouteImport.update({
  id: '/tools/$category/$toolSlug',
  path: '/tools/$category/$toolSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sdk': typeof SdkRoute
  '/stats': typeof StatsRouteWithChildren
  '/stats/offchain': typeof StatsOffchainRoute
  '/stats/onchain': typeof StatsOnchainRoute
  '/stats/package': typeof StatsPackageRoute
  '/stats/': typeof StatsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/tools/$category/$toolSlug': typeof ToolsCategoryToolSlugRoute
  '/tools/$category/': typeof ToolsCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sdk': typeof SdkRoute
  '/stats/offchain': typeof StatsOffchainRoute
  '/stats/onchain': typeof StatsOnchainRoute
  '/stats/package': typeof StatsPackageRoute
  '/stats': typeof StatsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/tools/$category/$toolSlug': typeof ToolsCategoryToolSlugRoute
  '/tools/$category': typeof ToolsCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sdk': typeof SdkRoute
  '/stats': typeof StatsRouteWithChildren
  '/stats/offchain': typeof StatsOffchainRoute
  '/stats/onchain': typeof StatsOnchainRoute
  '/stats/package': typeof StatsPackageRoute
  '/stats/': typeof StatsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/tools/$category/$toolSlug': typeof ToolsCategoryToolSlugRoute
  '/tools/$category/': typeof ToolsCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sdk'
    | '/stats'
    | '/stats/offchain'
    | '/stats/onchain'
    | '/stats/package'
    | '/stats/'
    | '/tools/'
    | '/tools/$category/$toolSlug'
    | '/tools/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sdk'
    | '/stats/offchain'
    | '/stats/onchain'
    | '/stats/package'
    | '/stats'
    | '/tools'
    | '/tools/$category/$toolSlug'
    | '/tools/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sdk'
    | '/stats'
    | '/stats/offchain'
    | '/stats/onchain'
    | '/stats/package'
    | '/stats/'
    | '/tools/'
    | '/tools/$category/$toolSlug'
    | '/tools/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SdkRoute: typeof SdkRoute
  StatsRoute: typeof StatsRouteWithChildren
  ToolsIndexRoute: typeof ToolsIndexRoute
  ToolsCategoryToolSlugRoute: typeof ToolsCategoryToolSlugRoute
  ToolsCategoryIndexRoute: typeof ToolsCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdk': {
      id: '/sdk'
      path: '/sdk'
      fullPath: '/sdk'
      preLoaderRoute: typeof SdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/'
      fullPath: '/stats/'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof StatsRoute
    }
    '/stats/package': {
      id: '/stats/package'
      path: '/package'
      fullPath: '/stats/package'
      preLoaderRoute: typeof StatsPackageRouteImport
      parentRoute: typeof StatsRoute
    }
    '/stats/onchain': {
      id: '/stats/onchain'
      path: '/onchain'
      fullPath: '/stats/onchain'
      preLoaderRoute: typeof StatsOnchainRouteImport
      parentRoute: typeof StatsRoute
    }
    '/stats/offchain': {
      id: '/stats/offchain'
      path: '/offchain'
      fullPath: '/stats/offchain'
      preLoaderRoute: typeof StatsOffchainRouteImport
      parentRoute: typeof StatsRoute
    }
    '/tools/$category/': {
      id: '/tools/$category/'
      path: '/tools/$category'
      fullPath: '/tools/$category/'
      preLoaderRoute: typeof ToolsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$category/$toolSlug': {
      id: '/tools/$category/$toolSlug'
      path: '/tools/$category/$toolSlug'
      fullPath: '/tools/$category/$toolSlug'
      preLoaderRoute: typeof ToolsCategoryToolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StatsRouteChildren {
  StatsOffchainRoute: typeof StatsOffchainRoute
  StatsOnchainRoute: typeof StatsOnchainRoute
  StatsPackageRoute: typeof StatsPackageRoute
  StatsIndexRoute: typeof StatsIndexRoute
}

const StatsRouteChildren: StatsRouteChildren = {
  StatsOffchainRoute: StatsOffchainRoute,
  StatsOnchainRoute: StatsOnchainRoute,
  StatsPackageRoute: StatsPackageRoute,
  StatsIndexRoute: StatsIndexRoute,
}

const StatsRouteWithChildren = StatsRoute._addFileChildren(StatsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SdkRoute: SdkRoute,
  StatsRoute: StatsRouteWithChildren,
  ToolsIndexRoute: ToolsIndexRoute,
  ToolsCategoryToolSlugRoute: ToolsCategoryToolSlugRoute,
  ToolsCategoryIndexRoute: ToolsCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
