/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as StatsIndexRouteImport } from './routes/stats.index'
import { Route as ToolsToolSlugRouteImport } from './routes/tools.$toolSlug'
import { Route as StatsPackageRouteImport } from './routes/stats.package'
import { Route as StatsOnchainRouteImport } from './routes/stats.onchain'
import { Route as ToolsCategoryToolSlugRouteImport } from './routes/tools.$category.$toolSlug'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StatsRoute,
} as any)
const ToolsToolSlugRoute = ToolsToolSlugRouteImport.update({
  id: '/tools/$toolSlug',
  path: '/tools/$toolSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsPackageRoute = StatsPackageRouteImport.update({
  id: '/package',
  path: '/package',
  getParentRoute: () => StatsRoute,
} as any)
const StatsOnchainRoute = StatsOnchainRouteImport.update({
  id: '/onchain',
  path: '/onchain',
  getParentRoute: () => StatsRoute,
} as any)
const ToolsCategoryToolSlugRoute = ToolsCategoryToolSlugRouteImport.update({
  id: '/tools/$category/$toolSlug',
  path: '/tools/$category/$toolSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stats': typeof StatsRouteWithChildren
  '/stats/onchain': typeof StatsOnchainRoute
  '/stats/package': typeof StatsPackageRoute
  '/tools/$toolSlug': typeof ToolsToolSlugRoute
  '/stats/': typeof StatsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/tools/$category/$toolSlug': typeof ToolsCategoryToolSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stats/onchain': typeof StatsOnchainRoute
  '/stats/package': typeof StatsPackageRoute
  '/tools/$toolSlug': typeof ToolsToolSlugRoute
  '/stats': typeof StatsIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/tools/$category/$toolSlug': typeof ToolsCategoryToolSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stats': typeof StatsRouteWithChildren
  '/stats/onchain': typeof StatsOnchainRoute
  '/stats/package': typeof StatsPackageRoute
  '/tools/$toolSlug': typeof ToolsToolSlugRoute
  '/stats/': typeof StatsIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/tools/$category/$toolSlug': typeof ToolsCategoryToolSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stats'
    | '/stats/onchain'
    | '/stats/package'
    | '/tools/$toolSlug'
    | '/stats/'
    | '/tools/'
    | '/tools/$category/$toolSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stats/onchain'
    | '/stats/package'
    | '/tools/$toolSlug'
    | '/stats'
    | '/tools'
    | '/tools/$category/$toolSlug'
  id:
    | '__root__'
    | '/'
    | '/stats'
    | '/stats/onchain'
    | '/stats/package'
    | '/tools/$toolSlug'
    | '/stats/'
    | '/tools/'
    | '/tools/$category/$toolSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatsRoute: typeof StatsRouteWithChildren
  ToolsToolSlugRoute: typeof ToolsToolSlugRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  ToolsCategoryToolSlugRoute: typeof ToolsCategoryToolSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/'
      fullPath: '/stats/'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof StatsRoute
    }
    '/tools/$toolSlug': {
      id: '/tools/$toolSlug'
      path: '/tools/$toolSlug'
      fullPath: '/tools/$toolSlug'
      preLoaderRoute: typeof ToolsToolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/package': {
      id: '/stats/package'
      path: '/package'
      fullPath: '/stats/package'
      preLoaderRoute: typeof StatsPackageRouteImport
      parentRoute: typeof StatsRoute
    }
    '/stats/onchain': {
      id: '/stats/onchain'
      path: '/onchain'
      fullPath: '/stats/onchain'
      preLoaderRoute: typeof StatsOnchainRouteImport
      parentRoute: typeof StatsRoute
    }
    '/tools/$category/$toolSlug': {
      id: '/tools/$category/$toolSlug'
      path: '/tools/$category/$toolSlug'
      fullPath: '/tools/$category/$toolSlug'
      preLoaderRoute: typeof ToolsCategoryToolSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StatsRouteChildren {
  StatsOnchainRoute: typeof StatsOnchainRoute
  StatsPackageRoute: typeof StatsPackageRoute
  StatsIndexRoute: typeof StatsIndexRoute
}

const StatsRouteChildren: StatsRouteChildren = {
  StatsOnchainRoute: StatsOnchainRoute,
  StatsPackageRoute: StatsPackageRoute,
  StatsIndexRoute: StatsIndexRoute,
}

const StatsRouteWithChildren = StatsRoute._addFileChildren(StatsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatsRoute: StatsRouteWithChildren,
  ToolsToolSlugRoute: ToolsToolSlugRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  ToolsCategoryToolSlugRoute: ToolsCategoryToolSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
