// Auto-generated by celina-sdk/scripts/generate-website-tools.mjs — do not edit by hand.
import type { ToolDoc } from "./tools.types.js";

export const GENERATED_HOSTED_TOOL_COUNT = 36;

export const GENERATED_TOOL_NAMES = ["get_network_status","get_block","get_latest_blocks","get_transaction","verify_attribution_tag","check_attribution_tag","get_wallet_address","get_account","get_celo_balances","get_stablecoin_balances","get_token_info","get_token_balance","estimate_send","send_token","get_gas_fee_data","estimate_transaction","get_mento_fx_quote","estimate_mento_fx","execute_mento_fx","get_uniswap_quote","estimate_uniswap_swap","execute_uniswap_swap","get_aave_balances","supply_aave","withdraw_aave","resolve_ens","get_gooddollar_whitelisting_info","get_gooddollar_identity_link","get_gooddollar_ubi_entitlement","claim_daily_gooddollar_ubi","get_gooddollar_reserve_quote","estimate_gooddollar_reserve_swap","execute_gooddollar_reserve_swap","get_governance_proposals","get_proposal_details","get_staking_balances","get_activatable_stakes","get_validator_groups","get_validator_group_details","get_total_staking_info","get_nft_info","get_nft_balance","call_contract_function","estimate_contract_gas","verify_self_agent","lookup_self_agent","verify_self_request","register_self_agent","check_self_registration","get_self_identity","refresh_self_proof","deregister_self_agent","sign_self_request","authenticated_self_fetch","get_agentkarma_reputation","get_agentkarma_celo_agent","check_agentkarma_counterparty"] as const;

export const GENERATED_TOOLS: Omit<ToolDoc, "returns">[] = [
  {
    "name": "get_network_status",
    "slug": "get-network-status",
    "title": "Get Network Status",
    "summary": "Returns Celo mainnet chain ID, latest block, and gas price.",
    "description": "Returns Celo mainnet chain ID, latest block, and gas price.",
    "kind": "read",
    "category": "Blockchain",
    "inputs": []
  },
  {
    "name": "get_block",
    "slug": "get-block",
    "title": "Get Block",
    "summary": "Fetch a Celo mainnet block by number, hash, or latest.",
    "description": "Fetch a Celo mainnet block by number, hash, or latest.",
    "kind": "read",
    "category": "Blockchain",
    "inputs": [
      {
        "name": "block_id",
        "type": "string",
        "required": true,
        "description": "block id"
      },
      {
        "name": "include_transactions",
        "type": "boolean",
        "required": false,
        "description": "include transactions"
      }
    ]
  },
  {
    "name": "get_latest_blocks",
    "slug": "get-latest-blocks",
    "title": "Get Latest Blocks",
    "summary": "Fetch the most recent blocks on Celo mainnet.",
    "description": "Fetch the most recent blocks on Celo mainnet.",
    "kind": "read",
    "category": "Blockchain",
    "inputs": [
      {
        "name": "count",
        "type": "string",
        "required": false,
        "description": "count"
      },
      {
        "name": "offset",
        "type": "string",
        "required": false,
        "description": "offset"
      }
    ]
  },
  {
    "name": "get_transaction",
    "slug": "get-transaction",
    "title": "Get Transaction",
    "summary": "Fetch a transaction and receipt by hash on Celo mainnet.",
    "description": "Fetch a transaction and receipt by hash on Celo mainnet.",
    "kind": "read",
    "category": "Blockchain",
    "inputs": [
      {
        "name": "hash",
        "type": "string",
        "required": true,
        "description": "hash"
      }
    ]
  },
  {
    "name": "verify_attribution_tag",
    "slug": "verify-attribution-tag",
    "title": "Verify Attribution Tag",
    "summary": "Decode legacy Celina (CELINA|…) and ERC-8021 (celina, app codes) attribution tags from a transaction's calldata on Celo mainnet.",
    "description": "Decode legacy Celina (CELINA|…) and ERC-8021 (celina, app codes) attribution tags from a transaction's calldata on Celo mainnet. Optionally pass tag to check for a specific code on either layer.",
    "kind": "read",
    "category": "Blockchain",
    "inputs": [
      {
        "name": "hash",
        "type": "string",
        "required": true,
        "description": "Transaction hash (0x + 64 hex characters)."
      },
      {
        "name": "tag",
        "type": "string",
        "required": false,
        "description": "Optional attribution code to match (e.g. celo_862c21dd97a7, MY_APP). Omit to decode all tags."
      }
    ]
  },
  {
    "name": "check_attribution_tag",
    "slug": "check-attribution-tag",
    "title": "Check Attribution Tag",
    "summary": "List custom attribution tags on a Celo mainnet transaction (unified tags array, excluding platform CELINA/celina), or check whether a specific tag is present.",
    "description": "List custom attribution tags on a Celo mainnet transaction (unified tags array, excluding platform CELINA/celina), or check whether a specific tag is present. Prefer this for “what tags are on this tx?”; use verify_attribution_tag for raw legacy/ERC-8021 layers only.",
    "kind": "read",
    "category": "Blockchain",
    "inputs": [
      {
        "name": "hash",
        "type": "string",
        "required": true,
        "description": "Transaction hash (0x + 64 hex characters)."
      },
      {
        "name": "tag",
        "type": "string",
        "required": false,
        "description": "Optional attribution code to match (e.g. celo_862c21dd97a7, MY_APP). Omit to list all custom tags."
      }
    ]
  },
  {
    "name": "get_wallet_address",
    "slug": "get-wallet-address",
    "title": "Get Wallet Address",
    "summary": "Returns the wallet address derived from CELO_PRIVATE_KEY in the MCP server env.",
    "description": "Returns the wallet address derived from CELO_PRIVATE_KEY in the MCP server env.",
    "kind": "read",
    "category": "Wallet",
    "inputs": []
  },
  {
    "name": "get_account",
    "slug": "get-account",
    "title": "Get Account",
    "summary": "Returns native CELO balance, nonce, and whether the address is a contract.",
    "description": "Returns native CELO balance, nonce, and whether the address is a contract.",
    "kind": "read",
    "category": "Account",
    "inputs": [
      {
        "name": "address",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      }
    ]
  },
  {
    "name": "get_celo_balances",
    "slug": "get-celo-balances",
    "title": "Get Celo Balances",
    "summary": "Balances for named registry tokens on Celo mainnet.",
    "description": "Balances for named registry tokens on Celo mainnet. Default tokens: CELO + USDm. Reads on-chain balances for the given address only; GoodDollar connected-wallet identity is not resolved.",
    "kind": "read",
    "category": "Token",
    "inputs": [
      {
        "name": "address",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      },
      {
        "name": "tokens",
        "type": "array",
        "required": false,
        "description": "tokens"
      }
    ]
  },
  {
    "name": "get_stablecoin_balances",
    "slug": "get-stablecoin-balances",
    "title": "Get Stablecoin Balances",
    "summary": "Scan fiat-pegged registry stablecoins (Mento *m, USDT, USDC, etc.",
    "description": "Scan fiat-pegged registry stablecoins (Mento *m, USDT, USDC, etc.) for an address in one call. Omits zero balances by default. Excludes GoodDollar (G$) and WETH — use get_token_balance or GoodDollar tools for those. Reads on-chain balances for the given address only; GoodDollar connected-wallet identity is not resolved.",
    "kind": "read",
    "category": "Token",
    "inputs": [
      {
        "name": "address",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      },
      {
        "name": "stablecoins",
        "type": "array",
        "required": false,
        "description": "stablecoins"
      },
      {
        "name": "include_zero",
        "type": "boolean",
        "required": false,
        "description": "include zero"
      }
    ]
  },
  {
    "name": "get_token_info",
    "slug": "get-token-info",
    "title": "Get Token Info",
    "summary": "Registry token metadata (symbol, address, decimals).",
    "description": "Registry token metadata (symbol, address, decimals). Does not read balances.",
    "kind": "read",
    "category": "Token",
    "inputs": [
      {
        "name": "token",
        "type": "string",
        "required": true,
        "description": "Celo mainnet token symbol (e.g. CELO, USDm, USDC, USDT)"
      }
    ]
  },
  {
    "name": "get_token_balance",
    "slug": "get-token-balance",
    "title": "Get Token Balance",
    "summary": "Balance for one registry token.",
    "description": "Balance for one registry token. Pass a symbol or known registry contract address. Reads on-chain balances for the given address only; GoodDollar connected-wallet identity is not resolved.",
    "kind": "read",
    "category": "Token",
    "inputs": [
      {
        "name": "token",
        "type": "string",
        "required": true,
        "description": "Celo mainnet token symbol (e.g. CELO, USDm, USDC, USDT)"
      },
      {
        "name": "address",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      }
    ]
  },
  {
    "name": "estimate_send",
    "slug": "estimate-send",
    "title": "Estimate Send",
    "summary": "Estimates gas for sending CELO or an ERC-20.",
    "description": "Estimates gas for sending CELO or an ERC-20. Recipient can be ENS.",
    "kind": "read",
    "category": "Transaction",
    "inputs": [
      {
        "name": "to",
        "type": "string",
        "required": true,
        "description": "Recipient 0x address or ENS name (e.g. andrewkimjoseph.celo.eth, celina.eth)"
      },
      {
        "name": "token",
        "type": "string",
        "required": false,
        "description": "Celo mainnet token symbol (e.g. CELO, USDm, USDC, USDT)"
      },
      {
        "name": "amount",
        "type": "string",
        "required": true,
        "description": "amount"
      },
      {
        "name": "from",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      }
    ]
  },
  {
    "name": "send_token",
    "slug": "send-token",
    "title": "Send Token",
    "summary": "Send CELO or an ERC-20 on mainnet.",
    "description": "Send CELO or an ERC-20 on mainnet. Requires CELO_PRIVATE_KEY in MCP server env.",
    "kind": "write",
    "category": "Transaction",
    "inputs": [
      {
        "name": "to",
        "type": "string",
        "required": true,
        "description": "Recipient 0x address or ENS name (e.g. andrewkimjoseph.celo.eth, celina.eth)"
      },
      {
        "name": "token",
        "type": "string",
        "required": false,
        "description": "Celo mainnet token symbol (e.g. CELO, USDm, USDC, USDT)"
      },
      {
        "name": "amount",
        "type": "string",
        "required": true,
        "description": "amount"
      }
    ]
  },
  {
    "name": "get_gas_fee_data",
    "slug": "get-gas-fee-data",
    "title": "Get Gas Fee Data",
    "summary": "Returns current gas fee data including EIP-1559 fees on mainnet.",
    "description": "Returns current gas fee data including EIP-1559 fees on mainnet.",
    "kind": "read",
    "category": "Blockchain",
    "inputs": []
  },
  {
    "name": "estimate_transaction",
    "slug": "estimate-transaction",
    "title": "Estimate Transaction",
    "summary": "Estimates gas for a generic transaction (to/value/data) from a wallet.",
    "description": "Estimates gas for a generic transaction (to/value/data) from a wallet.",
    "kind": "read",
    "category": "Blockchain",
    "inputs": [
      {
        "name": "from",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      },
      {
        "name": "to",
        "type": "string",
        "required": true,
        "description": "to"
      },
      {
        "name": "value",
        "type": "string",
        "required": false,
        "description": "value"
      },
      {
        "name": "data",
        "type": "string",
        "required": false,
        "description": "Optional transaction calldata (hex)"
      }
    ]
  },
  {
    "name": "get_mento_fx_quote",
    "slug": "get-mento-fx-quote",
    "title": "Get Mento FX Quote",
    "summary": "Mento FX oracle quote for a token pair on mainnet.",
    "description": "Mento FX oracle quote for a token pair on mainnet. Read-only.",
    "kind": "read",
    "category": "Mento FX",
    "inputs": [
      {
        "name": "token_in",
        "type": "string",
        "required": true,
        "description": "Input token symbol or address"
      },
      {
        "name": "token_out",
        "type": "string",
        "required": true,
        "description": "Output token symbol or address"
      },
      {
        "name": "amount",
        "type": "string",
        "required": true,
        "description": "Human-readable amount of token_in, e.g. 100"
      },
      {
        "name": "from",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      }
    ]
  },
  {
    "name": "estimate_mento_fx",
    "slug": "estimate-mento-fx",
    "title": "Estimate Mento FX",
    "summary": "Estimate gas for a Mento FX conversion including approval if needed.",
    "description": "Estimate gas for a Mento FX conversion including approval if needed.",
    "kind": "read",
    "category": "Mento FX",
    "inputs": [
      {
        "name": "token_in",
        "type": "string",
        "required": true,
        "description": "Input token symbol or address"
      },
      {
        "name": "token_out",
        "type": "string",
        "required": true,
        "description": "Output token symbol or address"
      },
      {
        "name": "amount",
        "type": "string",
        "required": true,
        "description": "Human-readable amount of token_in, e.g. 100"
      },
      {
        "name": "from",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      },
      {
        "name": "recipient",
        "type": "string",
        "required": false,
        "description": "Address that receives output tokens (defaults to signer)"
      },
      {
        "name": "slippage_tolerance",
        "type": "string",
        "required": false,
        "description": "Max slippage in percent (default 0.5)"
      },
      {
        "name": "deadline_minutes",
        "type": "string",
        "required": false,
        "description": "Transaction deadline in minutes (default 5)"
      }
    ]
  },
  {
    "name": "execute_mento_fx",
    "slug": "execute-mento-fx",
    "title": "Execute Mento FX",
    "summary": "Execute a Mento FX conversion on mainnet.",
    "description": "Execute a Mento FX conversion on mainnet. Requires CELO_PRIVATE_KEY.",
    "kind": "write",
    "category": "Mento FX",
    "inputs": [
      {
        "name": "token_in",
        "type": "string",
        "required": true,
        "description": "Input token symbol or address"
      },
      {
        "name": "token_out",
        "type": "string",
        "required": true,
        "description": "Output token symbol or address"
      },
      {
        "name": "amount",
        "type": "string",
        "required": true,
        "description": "Human-readable amount of token_in, e.g. 100"
      },
      {
        "name": "from",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      },
      {
        "name": "recipient",
        "type": "string",
        "required": false,
        "description": "Address that receives output tokens (defaults to signer)"
      },
      {
        "name": "slippage_tolerance",
        "type": "string",
        "required": false,
        "description": "Max slippage in percent (default 0.5)"
      },
      {
        "name": "deadline_minutes",
        "type": "string",
        "required": false,
        "description": "Transaction deadline in minutes (default 5)"
      }
    ]
  },
  {
    "name": "get_uniswap_quote",
    "slug": "get-uniswap-quote",
    "title": "Get Uniswap Quote",
    "summary": "Uniswap v4 AMM quote for a token pair on Celo mainnet.",
    "description": "Uniswap v4 AMM quote for a token pair on Celo mainnet.",
    "kind": "read",
    "category": "Uniswap",
    "inputs": [
      {
        "name": "token_in",
        "type": "string",
        "required": true,
        "description": "Celo mainnet token symbol (e.g. CELO, USDm, USDC, USDT)"
      },
      {
        "name": "token_out",
        "type": "string",
        "required": true,
        "description": "Celo mainnet token symbol (e.g. CELO, USDm, USDC, USDT)"
      },
      {
        "name": "amount",
        "type": "string",
        "required": true,
        "description": "Human-readable amount of token_in"
      },
      {
        "name": "from",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      }
    ]
  },
  {
    "name": "estimate_uniswap_swap",
    "slug": "estimate-uniswap-swap",
    "title": "Estimate Uniswap Swap",
    "summary": "Estimate gas for a Uniswap v4 swap including ERC-20 and Permit2 approvals when needed.",
    "description": "Estimate gas for a Uniswap v4 swap including ERC-20 and Permit2 approvals when needed.",
    "kind": "read",
    "category": "Uniswap",
    "inputs": [
      {
        "name": "token_in",
        "type": "string",
        "required": true,
        "description": "Celo mainnet token symbol (e.g. CELO, USDm, USDC, USDT)"
      },
      {
        "name": "token_out",
        "type": "string",
        "required": true,
        "description": "Celo mainnet token symbol (e.g. CELO, USDm, USDC, USDT)"
      },
      {
        "name": "amount",
        "type": "string",
        "required": true,
        "description": "Human-readable amount of token_in"
      },
      {
        "name": "from",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      },
      {
        "name": "recipient",
        "type": "string",
        "required": false,
        "description": "recipient"
      },
      {
        "name": "slippage_tolerance",
        "type": "string",
        "required": false,
        "description": "slippage tolerance"
      },
      {
        "name": "deadline_minutes",
        "type": "string",
        "required": false,
        "description": "deadline minutes"
      }
    ]
  },
  {
    "name": "execute_uniswap_swap",
    "slug": "execute-uniswap-swap",
    "title": "Execute Uniswap Swap",
    "summary": "Execute a Uniswap v4 swap on Celo mainnet.",
    "description": "Execute a Uniswap v4 swap on Celo mainnet. Requires CELO_PRIVATE_KEY.",
    "kind": "write",
    "category": "Uniswap",
    "inputs": [
      {
        "name": "token_in",
        "type": "string",
        "required": true,
        "description": "Celo mainnet token symbol (e.g. CELO, USDm, USDC, USDT)"
      },
      {
        "name": "token_out",
        "type": "string",
        "required": true,
        "description": "Celo mainnet token symbol (e.g. CELO, USDm, USDC, USDT)"
      },
      {
        "name": "amount",
        "type": "string",
        "required": true,
        "description": "Human-readable amount of token_in"
      },
      {
        "name": "from",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      },
      {
        "name": "recipient",
        "type": "string",
        "required": false,
        "description": "recipient"
      },
      {
        "name": "slippage_tolerance",
        "type": "string",
        "required": false,
        "description": "slippage tolerance"
      },
      {
        "name": "deadline_minutes",
        "type": "string",
        "required": false,
        "description": "deadline minutes"
      }
    ]
  },
  {
    "name": "get_aave_balances",
    "slug": "get-aave-balances",
    "title": "Get Aave Balances",
    "summary": "Read supplied Aave V3 balances (aToken holdings) on Celo in underlying token units including accrued interest.",
    "description": "Read supplied Aave V3 balances (aToken holdings) on Celo in underlying token units including accrued interest. Each balance has formatted (human-readable, e.g. \"0.000002\") and raw (atomic units — do not quote raw to users). Supported: USDT, WETH, USDm, USDC, CELO, EURm. Omit address to use the session wallet when CELO_PRIVATE_KEY is set.",
    "kind": "read",
    "category": "Aave",
    "inputs": [
      {
        "name": "address",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      },
      {
        "name": "tokens",
        "type": "array",
        "required": false,
        "description": "tokens"
      },
      {
        "name": "include_zero",
        "type": "boolean",
        "required": false,
        "description": "include zero"
      }
    ]
  },
  {
    "name": "supply_aave",
    "slug": "supply-aave",
    "title": "Supply Aave",
    "summary": "Supply tokens to Aave V3 on Celo.",
    "description": "Supply tokens to Aave V3 on Celo. Supported: USDT, WETH, USDm, USDC, CELO, EURm. Requires CELO_PRIVATE_KEY.",
    "kind": "write",
    "category": "Aave",
    "inputs": [
      {
        "name": "token",
        "type": "string",
        "required": true,
        "description": "Aave asset symbol on Celo (USDT, WETH, USDm, USDC, CELO, EURm). Pass the symbol only."
      },
      {
        "name": "amount",
        "type": "string",
        "required": true,
        "description": "amount"
      }
    ]
  },
  {
    "name": "withdraw_aave",
    "slug": "withdraw-aave",
    "title": "Withdraw Aave",
    "summary": "Withdraw tokens from Aave V3 on Celo.",
    "description": "Withdraw tokens from Aave V3 on Celo. Supported: USDT, WETH, USDm, USDC, CELO, EURm. Requires CELO_PRIVATE_KEY.",
    "kind": "write",
    "category": "Aave",
    "inputs": [
      {
        "name": "token",
        "type": "string",
        "required": true,
        "description": "Aave asset symbol on Celo (USDT, WETH, USDm, USDC, CELO, EURm). Pass the symbol only."
      },
      {
        "name": "amount",
        "type": "string",
        "required": false,
        "description": "amount"
      },
      {
        "name": "withdraw_max",
        "type": "boolean",
        "required": false,
        "description": "withdraw max"
      }
    ]
  },
  {
    "name": "resolve_ens",
    "slug": "resolve-ens",
    "title": "Resolve ENS",
    "summary": "Resolve a Celo or Ethereum ENS name to an address.",
    "description": "Resolve a Celo or Ethereum ENS name to an address. Defaults to Celo coin record with Ethereum fallback.",
    "kind": "read",
    "category": "Wallet",
    "inputs": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "ENS name, e.g. celina.eth or andrewkimjoseph.celo.eth"
      },
      {
        "name": "chain",
        "type": "string",
        "required": false,
        "description": "chain"
      }
    ]
  },
  {
    "name": "get_gooddollar_whitelisting_info",
    "slug": "get-gooddollar-whitelisting-info",
    "title": "Get GoodDollar Whitelisting Info",
    "summary": "Check GoodDollar IdentityV4 whitelist status for a wallet.",
    "description": "Check GoodDollar IdentityV4 whitelist status for a wallet. Connected wallets resolve to their verified root; returns isWhitelisted, whitelistedRoot, and checkedAddress.",
    "kind": "read",
    "category": "GoodDollar",
    "inputs": [
      {
        "name": "address",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      }
    ]
  },
  {
    "name": "get_gooddollar_identity_link",
    "slug": "get-gooddollar-identity-link",
    "title": "Get GoodDollar Identity Link",
    "summary": "How a wallet links to GoodDollar IdentityV4: whitelisted root, connected-to root, and live whitelist status.",
    "description": "How a wallet links to GoodDollar IdentityV4: whitelisted root, connected-to root, and live whitelist status.",
    "kind": "read",
    "category": "GoodDollar",
    "inputs": [
      {
        "name": "address",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      }
    ]
  },
  {
    "name": "get_gooddollar_ubi_entitlement",
    "slug": "get-gooddollar-ubi-entitlement",
    "title": "Get GoodDollar UBI Entitlement",
    "summary": "Daily GoodDollar UBI claim eligibility: whitelist root, claimable G$, already claimed.",
    "description": "Daily GoodDollar UBI claim eligibility: whitelist root, claimable G$, already claimed. Nested identity.isWhitelisted reflects the resolved root.",
    "kind": "read",
    "category": "GoodDollar",
    "inputs": [
      {
        "name": "address",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      }
    ]
  },
  {
    "name": "claim_daily_gooddollar_ubi",
    "slug": "claim-daily-gooddollar-ubi",
    "title": "Claim Daily GoodDollar UBI",
    "summary": "Claim today's GoodDollar UBI for the MCP server wallet.",
    "description": "Claim today's GoodDollar UBI for the MCP server wallet. Requires CELO_PRIVATE_KEY.",
    "kind": "write",
    "category": "GoodDollar",
    "inputs": []
  },
  {
    "name": "get_gooddollar_reserve_quote",
    "slug": "get-gooddollar-reserve-quote",
    "title": "Get GoodDollar Reserve Quote",
    "summary": "GoodDollar reserve quote for G$ ↔ USDm on Celo (MentoBroker bonding curve).",
    "description": "GoodDollar reserve quote for G$ ↔ USDm on Celo (MentoBroker bonding curve). Use amount_side \"out\" when the user names the amount they want to receive (e.g. \"get 0.6 USDm\"). Uses the literal signing wallet address for balances; does not resolve GoodDollar identity roots.",
    "kind": "read",
    "category": "GoodDollar",
    "inputs": [
      {
        "name": "token_in",
        "type": "string",
        "required": true,
        "description": "GoodDollar or G$"
      },
      {
        "name": "token_out",
        "type": "string",
        "required": true,
        "description": "USDm or cUSD"
      },
      {
        "name": "amount",
        "type": "string",
        "required": true,
        "description": "Human-readable amount; paired with amount_side (in = spend, out = receive)"
      },
      {
        "name": "amount_side",
        "type": "string",
        "required": false,
        "description": "'in': amount is token_in spend (default). 'out': amount is desired token_out receive amount."
      },
      {
        "name": "from",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      }
    ]
  },
  {
    "name": "estimate_gooddollar_reserve_swap",
    "slug": "estimate-gooddollar-reserve-swap",
    "title": "Estimate GoodDollar Reserve Swap",
    "summary": "Estimate gas for a GoodDollar reserve swap (G$ ↔ USDm), including ERC-20 approval when needed.",
    "description": "Estimate gas for a GoodDollar reserve swap (G$ ↔ USDm), including ERC-20 approval when needed. Uses the literal signing wallet address for balances; does not resolve GoodDollar identity roots.",
    "kind": "read",
    "category": "GoodDollar",
    "inputs": [
      {
        "name": "token_in",
        "type": "string",
        "required": true,
        "description": "GoodDollar or G$"
      },
      {
        "name": "token_out",
        "type": "string",
        "required": true,
        "description": "USDm or cUSD"
      },
      {
        "name": "amount",
        "type": "string",
        "required": true,
        "description": "Human-readable amount; paired with amount_side (in = spend, out = receive)"
      },
      {
        "name": "amount_side",
        "type": "string",
        "required": false,
        "description": "'in': amount is token_in spend (default). 'out': amount is desired token_out receive amount."
      },
      {
        "name": "from",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      },
      {
        "name": "recipient",
        "type": "string",
        "required": false,
        "description": "recipient"
      },
      {
        "name": "slippage_tolerance",
        "type": "string",
        "required": false,
        "description": "slippage tolerance"
      }
    ]
  },
  {
    "name": "execute_gooddollar_reserve_swap",
    "slug": "execute-gooddollar-reserve-swap",
    "title": "Execute GoodDollar Reserve Swap",
    "summary": "Execute a GoodDollar reserve swap (G$ ↔ USDm) on mainnet.",
    "description": "Execute a GoodDollar reserve swap (G$ ↔ USDm) on mainnet. Requires CELO_PRIVATE_KEY.",
    "kind": "write",
    "category": "GoodDollar",
    "inputs": [
      {
        "name": "token_in",
        "type": "string",
        "required": true,
        "description": "GoodDollar or G$"
      },
      {
        "name": "token_out",
        "type": "string",
        "required": true,
        "description": "USDm or cUSD"
      },
      {
        "name": "amount",
        "type": "string",
        "required": true,
        "description": "Human-readable amount; paired with amount_side (in = spend, out = receive)"
      },
      {
        "name": "amount_side",
        "type": "string",
        "required": false,
        "description": "'in': amount is token_in spend (default). 'out': amount is desired token_out receive amount."
      },
      {
        "name": "from",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      },
      {
        "name": "recipient",
        "type": "string",
        "required": false,
        "description": "recipient"
      },
      {
        "name": "slippage_tolerance",
        "type": "string",
        "required": false,
        "description": "slippage tolerance"
      }
    ]
  },
  {
    "name": "get_governance_proposals",
    "slug": "get-governance-proposals",
    "title": "Get Governance Proposals",
    "summary": "Returns Celo governance proposals with pagination.",
    "description": "Returns Celo governance proposals with pagination. Set include_metadata=false for faster responses.",
    "kind": "read",
    "category": "Governance",
    "inputs": [
      {
        "name": "include_inactive",
        "type": "string",
        "required": true,
        "description": "include inactive"
      },
      {
        "name": "include_metadata",
        "type": "string",
        "required": true,
        "description": "include metadata"
      },
      {
        "name": "page",
        "type": "string",
        "required": false,
        "description": "page"
      },
      {
        "name": "page_size",
        "type": "string",
        "required": false,
        "description": "page size"
      },
      {
        "name": "offset",
        "type": "string",
        "required": false,
        "description": "offset"
      },
      {
        "name": "limit",
        "type": "string",
        "required": false,
        "description": "limit"
      }
    ]
  },
  {
    "name": "get_proposal_details",
    "slug": "get-proposal-details",
    "title": "Get Proposal Details",
    "summary": "Returns detailed information about a Celo governance proposal.",
    "description": "Returns detailed information about a Celo governance proposal.",
    "kind": "read",
    "category": "Governance",
    "inputs": [
      {
        "name": "proposal_id",
        "type": "string",
        "required": true,
        "description": "proposal id"
      }
    ]
  },
  {
    "name": "get_staking_balances",
    "slug": "get-staking-balances",
    "title": "Get Staking Balances",
    "summary": "Active and pending staking votes for an address by validator group.",
    "description": "Active and pending staking votes for an address by validator group.",
    "kind": "read",
    "category": "Staking",
    "inputs": [
      {
        "name": "address",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      }
    ]
  },
  {
    "name": "get_activatable_stakes",
    "slug": "get-activatable-stakes",
    "title": "Get Activatable Stakes",
    "summary": "Validator groups where pending stakes can be activated for an address.",
    "description": "Validator groups where pending stakes can be activated for an address.",
    "kind": "read",
    "category": "Staking",
    "inputs": [
      {
        "name": "address",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      }
    ]
  },
  {
    "name": "get_validator_groups",
    "slug": "get-validator-groups",
    "title": "Get Validator Groups",
    "summary": "Paginated validator groups with votes, capacity, and member counts.",
    "description": "Paginated validator groups with votes, capacity, and member counts.",
    "kind": "read",
    "category": "Staking",
    "inputs": [
      {
        "name": "page",
        "type": "string",
        "required": false,
        "description": "page"
      },
      {
        "name": "page_size",
        "type": "string",
        "required": false,
        "description": "page size"
      },
      {
        "name": "offset",
        "type": "string",
        "required": false,
        "description": "offset"
      },
      {
        "name": "limit",
        "type": "string",
        "required": false,
        "description": "limit"
      }
    ]
  },
  {
    "name": "get_validator_group_details",
    "slug": "get-validator-group-details",
    "title": "Get Validator Group Details",
    "summary": "Detailed information about a validator group including members.",
    "description": "Detailed information about a validator group including members.",
    "kind": "read",
    "category": "Staking",
    "inputs": [
      {
        "name": "group_address",
        "type": "string",
        "required": true,
        "description": "group address"
      }
    ]
  },
  {
    "name": "get_total_staking_info",
    "slug": "get-total-staking-info",
    "title": "Get Total Staking Info",
    "summary": "Network-wide staking participation metrics.",
    "description": "Network-wide staking participation metrics.",
    "kind": "read",
    "category": "Staking",
    "inputs": []
  },
  {
    "name": "get_nft_info",
    "slug": "get-nft-info",
    "title": "Get NFT Info",
    "summary": "NFT token information including metadata for ERC-721 or ERC-1155.",
    "description": "NFT token information including metadata for ERC-721 or ERC-1155.",
    "kind": "read",
    "category": "NFT",
    "inputs": [
      {
        "name": "contract_address",
        "type": "string",
        "required": true,
        "description": "contract address"
      },
      {
        "name": "token_id",
        "type": "string",
        "required": true,
        "description": "NFT token ID (decimal string)"
      }
    ]
  },
  {
    "name": "get_nft_balance",
    "slug": "get-nft-balance",
    "title": "Get NFT Balance",
    "summary": "NFT balance for an address.",
    "description": "NFT balance for an address. Token ID required for ERC-1155.",
    "kind": "read",
    "category": "NFT",
    "inputs": [
      {
        "name": "contract_address",
        "type": "string",
        "required": true,
        "description": "contract address"
      },
      {
        "name": "address",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      },
      {
        "name": "token_id",
        "type": "string",
        "required": false,
        "description": "NFT token ID (decimal string)"
      }
    ]
  },
  {
    "name": "call_contract_function",
    "slug": "call-contract-function",
    "title": "Call Contract Function",
    "summary": "Calls a read-only contract function.",
    "description": "Calls a read-only contract function. Requires caller-supplied ABI JSON.",
    "kind": "read",
    "category": "Contract",
    "inputs": [
      {
        "name": "contract_address",
        "type": "string",
        "required": true,
        "description": "contract address"
      },
      {
        "name": "function_name",
        "type": "string",
        "required": true,
        "description": "function name"
      },
      {
        "name": "abi",
        "type": "array",
        "required": true,
        "description": "Contract ABI as a JSON array"
      },
      {
        "name": "function_args",
        "type": "array",
        "required": false,
        "description": "function args"
      },
      {
        "name": "from_address",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      }
    ]
  },
  {
    "name": "estimate_contract_gas",
    "slug": "estimate-contract-gas",
    "title": "Estimate Contract Gas",
    "summary": "Estimates gas for a contract function call.",
    "description": "Estimates gas for a contract function call. Requires caller-supplied ABI JSON.",
    "kind": "read",
    "category": "Contract",
    "inputs": [
      {
        "name": "contract_address",
        "type": "string",
        "required": true,
        "description": "contract address"
      },
      {
        "name": "function_name",
        "type": "string",
        "required": true,
        "description": "function name"
      },
      {
        "name": "abi",
        "type": "array",
        "required": true,
        "description": "Contract ABI as a JSON array"
      },
      {
        "name": "function_args",
        "type": "array",
        "required": false,
        "description": "function args"
      },
      {
        "name": "value",
        "type": "string",
        "required": false,
        "description": "value"
      },
      {
        "name": "from",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      },
      {
        "name": "from_address",
        "type": "string",
        "required": false,
        "description": "Wallet on Celo mainnet. Omit to use the connected wallet or MCP CELO_PRIVATE_KEY signer."
      }
    ]
  },
  {
    "name": "verify_self_agent",
    "slug": "verify-self-agent",
    "title": "Verify Self Agent",
    "summary": "Verify whether an agent address is backed by a real human on Self Agent ID (Celo mainnet).",
    "description": "Verify whether an agent address is backed by a real human on Self Agent ID (Celo mainnet).",
    "kind": "read",
    "category": "Self",
    "inputs": [
      {
        "name": "agent_address",
        "type": "string",
        "required": true,
        "description": "agent address"
      },
      {
        "name": "require_age",
        "type": "string",
        "required": true,
        "description": "require age"
      },
      {
        "name": "require_ofac",
        "type": "string",
        "required": true,
        "description": "require ofac"
      },
      {
        "name": "require_self_provider",
        "type": "string",
        "required": true,
        "description": "require self provider"
      }
    ]
  },
  {
    "name": "lookup_self_agent",
    "slug": "lookup-self-agent",
    "title": "Look Up Self Agent",
    "summary": "Look up a Self Agent ID by numeric on-chain ID.",
    "description": "Look up a Self Agent ID by numeric on-chain ID.",
    "kind": "read",
    "category": "Self",
    "inputs": [
      {
        "name": "agent_id",
        "type": "string",
        "required": true,
        "description": "agent id"
      }
    ]
  },
  {
    "name": "verify_self_request",
    "slug": "verify-self-request",
    "title": "Verify Self Agent Request",
    "summary": "Verify incoming HTTP request headers signed by a Self Agent (not file system access).",
    "description": "Verify incoming HTTP request headers signed by a Self Agent (not file system access).",
    "kind": "read",
    "category": "Self",
    "inputs": [
      {
        "name": "agent_signature",
        "type": "string",
        "required": true,
        "description": "agent signature"
      },
      {
        "name": "agent_timestamp",
        "type": "string",
        "required": true,
        "description": "agent timestamp"
      },
      {
        "name": "method",
        "type": "string",
        "required": true,
        "description": "method"
      },
      {
        "name": "request_path",
        "type": "string",
        "required": true,
        "description": "request path"
      },
      {
        "name": "body",
        "type": "string",
        "required": true,
        "description": "body"
      },
      {
        "name": "keytype",
        "type": "string",
        "required": true,
        "description": "keytype"
      },
      {
        "name": "agent_key",
        "type": "string",
        "required": true,
        "description": "agent key"
      }
    ]
  },
  {
    "name": "register_self_agent",
    "slug": "register-self-agent",
    "title": "Register Self Agent",
    "summary": "Start Self Agent ID registration.",
    "description": "Start Self Agent ID registration. Returns qr_code_url and deep_link — present BOTH to the user.",
    "kind": "write",
    "category": "Self",
    "inputs": [
      {
        "name": "mode",
        "type": "string",
        "required": true,
        "description": "mode"
      },
      {
        "name": "minimum_age",
        "type": "string",
        "required": true,
        "description": "minimum age"
      },
      {
        "name": "ofac",
        "type": "string",
        "required": true,
        "description": "ofac"
      },
      {
        "name": "human_address",
        "type": "string",
        "required": false,
        "description": "human address"
      },
      {
        "name": "agent_name",
        "type": "string",
        "required": true,
        "description": "agent name"
      },
      {
        "name": "agent_description",
        "type": "string",
        "required": true,
        "description": "agent description"
      }
    ]
  },
  {
    "name": "check_self_registration",
    "slug": "check-self-registration",
    "title": "Check Self Registration",
    "summary": "Poll a pending Self registration, proof refresh, or deregistration session.",
    "description": "Poll a pending Self registration, proof refresh, or deregistration session.",
    "kind": "read",
    "category": "Self",
    "inputs": [
      {
        "name": "session_id",
        "type": "string",
        "required": true,
        "description": "session id"
      }
    ]
  },
  {
    "name": "get_self_identity",
    "slug": "get-self-identity",
    "title": "Get Self Agent Identity",
    "summary": "Return the configured Self agent identity.",
    "description": "Return the configured Self agent identity. Requires SELF_AGENT_PRIVATE_KEY.",
    "kind": "read",
    "category": "Self",
    "inputs": []
  },
  {
    "name": "refresh_self_proof",
    "slug": "refresh-self-proof",
    "title": "Refresh Self Proof",
    "summary": "Start a human proof refresh after on-chain proof expiry.",
    "description": "Start a human proof refresh after on-chain proof expiry. Returns qr_code_url and deep_link.",
    "kind": "write",
    "category": "Self",
    "inputs": [
      {
        "name": "agent_id",
        "type": "string",
        "required": true,
        "description": "agent id"
      }
    ]
  },
  {
    "name": "deregister_self_agent",
    "slug": "deregister-self-agent",
    "title": "Deregister Self Agent",
    "summary": "Start irreversible Self agent deregistration.",
    "description": "Start irreversible Self agent deregistration. Returns qr_code_url and deep_link.",
    "kind": "write",
    "category": "Self",
    "inputs": []
  },
  {
    "name": "sign_self_request",
    "slug": "sign-self-request",
    "title": "Sign Self Agent Request",
    "summary": "Sign an HTTP request with the configured Self agent.",
    "description": "Sign an HTTP request with the configured Self agent. Demo verify: POST https://app.ai.self.xyz/api/demo/verify?network=celo-mainnet",
    "kind": "read",
    "category": "Self",
    "inputs": [
      {
        "name": "method",
        "type": "string",
        "required": true,
        "description": "method"
      },
      {
        "name": "url",
        "type": "string",
        "required": true,
        "description": "url"
      },
      {
        "name": "body",
        "type": "string",
        "required": true,
        "description": "body"
      }
    ]
  },
  {
    "name": "authenticated_self_fetch",
    "slug": "authenticated-self-fetch",
    "title": "Authenticated Self Fetch",
    "summary": "HTTP request with Self Agent ID auth headers.",
    "description": "HTTP request with Self Agent ID auth headers. Demo: ?network=celo-mainnet — https://app.ai.self.xyz/api/demo/verify?network=celo-mainnet",
    "kind": "write",
    "category": "Self",
    "inputs": [
      {
        "name": "method",
        "type": "string",
        "required": true,
        "description": "method"
      },
      {
        "name": "url",
        "type": "string",
        "required": true,
        "description": "url"
      },
      {
        "name": "body",
        "type": "string",
        "required": true,
        "description": "body"
      },
      {
        "name": "content_type",
        "type": "string",
        "required": true,
        "description": "content type"
      }
    ]
  },
  {
    "name": "get_agentkarma_reputation",
    "slug": "get-agentkarma-reputation",
    "title": "Get AgentKarma Reputation",
    "summary": "Read AgentKarma Provider + Consumer reputation for a Celo agent wallet (read-only, agentkarma.",
    "description": "Read AgentKarma Provider + Consumer reputation for a Celo agent wallet (read-only, agentkarma.io). Optional trust context — never routes, signs, or holds custody.",
    "kind": "read",
    "category": "AgentKarma",
    "inputs": [
      {
        "name": "address",
        "type": "string",
        "required": true,
        "description": "Celo 0x address of the agent/counterparty to look up."
      },
      {
        "name": "face",
        "type": "string",
        "required": true,
        "description": "Karma face to read: provider, consumer, or both (default)."
      }
    ]
  },
  {
    "name": "get_agentkarma_celo_agent",
    "slug": "get-agentkarma-celo-agent",
    "title": "Get AgentKarma Celo Agent",
    "summary": "Resolve a Celo ERC-8004 agent (identity + reputation) by numeric agent ID via AgentKarma (read-only).",
    "description": "Resolve a Celo ERC-8004 agent (identity + reputation) by numeric agent ID via AgentKarma (read-only).",
    "kind": "read",
    "category": "AgentKarma",
    "inputs": [
      {
        "name": "agent_id",
        "type": "string",
        "required": true,
        "description": "ERC-8004 agent ID on Celo."
      }
    ]
  },
  {
    "name": "check_agentkarma_counterparty",
    "slug": "check-agentkarma-counterparty",
    "title": "Check AgentKarma Counterparty",
    "summary": "Evaluate a Celo counterparty against a local AgentKarma trust policy (min score, receipt-backed).",
    "description": "Evaluate a Celo counterparty against a local AgentKarma trust policy (min score, receipt-backed). Returns an explainable allow/deny decision plus the snapshot it read. Read-only — never routes, signs, or holds custody.",
    "kind": "read",
    "category": "AgentKarma",
    "inputs": [
      {
        "name": "address",
        "type": "string",
        "required": true,
        "description": "Celo 0x address of the agent/counterparty to look up."
      },
      {
        "name": "face",
        "type": "string",
        "required": true,
        "description": "Face to score the decision on (default provider)."
      },
      {
        "name": "min_score",
        "type": "string",
        "required": true,
        "description": "Reject when the face score is below this (0–100)."
      },
      {
        "name": "require_receipt_backed",
        "type": "string",
        "required": true,
        "description": "Require at least one Tier-1 receipt-backed signal on the face."
      }
    ]
  }
];
